/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function rustInitialize(): number
export declare function rustFilter(): object
export declare function filterWithCallback(callback: (user: {id: number, firstName: string, age: number, role: string}) => boolean): Promise<number>
export declare function filterWithCallbackSync(callback: (user: {id: number, firstName: string, age: number, role: string}) => boolean): object
